### PR TITLE
Fix uninformative error messages and allow not only strings to be used as keys

### LINKED ISSUE #3: Typescript error is not informative if a provided key is not a key of store slice
image

But if a correct key is provided, the error will disappear. 

image

This is a known issue without a good idea to fix. If you know how to fix if, please make a PR or let me know here.

### PR DESCRIPTION
**Pull request by ivteplo**
To fix #3, I:
- updated `Key` type to be `Key<T> = keyof T`, since the part ` & string & KEY` caused the difficult-to-understand error message
- removed `KEY` part from all generics
- updated some parts of `listenChange` (now the value of a state item is saved into a variable, and `Symbol.for` is not being used)
- combined `useChange` function definitions just into one function without overrides, since this caused extremely long error message

And also I found out that I couldn't use numbers as keys, because TypeScript would throw an error. Example:
```ts
// ...

interface RootState {
  0: string
}

// ...

useChange((state: RootState), 0) // would throw an error
```

So I updated `WeakMap<any, Record<string, Handler[]>>` to `WeakMap<any, Record<any, Handler[]>>`

### CODE REVIEW

**Comment by ivteplo** [comment]
**Resulting message:**

Error message example

**Comment by finom** [comment]
Looks great, thank you! 🎉  That's a very important fix.
I've published a beta version https://www.npmjs.com/package/use-change/v/1.0.4-beta.1 to test it in a real product and will merge the PR after that.

A few notes to myself before publish a non-beta release:

- Rename `getSlice` into `useSlice` to remove disabled `react-hooks/rules-of-hooks` rule.
- Remove `any` from `useValue`
- Remove `Key<SLICE>` and replace by `keyof SLICE` (?)
- Add test for numbers and symbols as keys
- Update documentation by replacing `K & keyof T & string` by `keyof T`

P. S. I've used `Symbol.for(...)` to see values at console without expanding a property. But you're right, it may annoy that size of an object at dev tools is doubling.

**Comment by finom** [comment]
There is a bug. Resulting value has type that intersects all types of all values of its object  :( That's why I've used al those weird generics.

image

`value` supposed to be recognised as a `number`.

**Comment by ivteplo** [comment]
Oh, I see. I'll try to find out whether there is a way to fix this

**Comment by ivteplo** [comment]
@finom I've made some updates to type definitions. Looks like it works as it should
Screenshot that shows that type gets recognized correctly

And error message when using a non-existent key are still informative
Screenshot that shows that error messages are still informative

**Comment by finom** [comment]
Great! Published as https://www.npmjs.com/package/use-change/v/1.0.4-beta.2

**Comment by finom** [comment]
@ivteplo can you please rename generic arguments back to uppercased? It helps to visually determine generic declaration and generic arguments when they used.

**Comment by ivteplo** [comment]
Ok, I'll do that a bit later

**Comment by finom** [comment]
Code is much cleaner now without those overloads. Thank you very much! 🥇

**Comment by finom** [comment]
@ivteplo added you to contributors section https://github.com/finom/use-change#contributors- 🎉

**Comment by ivteplo** [comment]
@finom Thank you! 😊

**Pull request merged**
